[package]
name = "yoga"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.30.0"
gcc = "0.3"

[dependencies]
ordered-float = "0.5.0"
